version: "3.8"

services:

  python:
    image: &image kwiliarty/glyphworks:main
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=main.settings.test
    expose:
      - '8000'
    command: ['daphne', '-b', '0.0.0.0', '-p', '8000', 'main.asgi:application']
    volumes:
      &volumes
      - static_volume:/usr/src/app/static
      - type: bind
        source: ./../
        target: /usr/src/app

  nginx:
    image: nginx:1.20.2-alpine
    ports:
      - "${GW_PYTHON_PORT}:80"
      - '443:443'
    volumes:
      - static_volume:/usr/src/app/static
      - type: bind
        source: ./nginx/test/conf.d/
        target: /etc/nginx/conf.d/
      - type: bind
        source: ./nginx/test/ssl
        target: /etc/ssl/gw
    depends_on:
      - python
    restart: 'on-failure'
    networks:
      - django

  # celery:
  #   image: *image
  #   environment:
  #     - DJANGO_SETTINGS_MODULE=main.settings.test
  #   volumes:
  #     *volumes

  # celery-beat:
  #   image: *image
  #   environment:
  #     - DJANGO_SETTINGS_MODULE=main.settings.test
  #   volumes:
  #     *volumes
volumes:
  static_volume:
